.\" Manpage for maim.
.\" Contact naelstrof@gmail.com to correct errors or typos.
.TH maim 1 2017-03-21 Linux "maim man page"
.SH NAME
maim \- make image
.SH SYNOPSIS
maim [OPTIONS] [FILEPATH]
.SH DESCRIPTION
maim (make image) is an utility that takes a screenshot of your desktop, and encodes a png or jpg image of it. By default it outputs the encoded image data directly to standard output.
.SH OPTIONS
.TP
.BR \-h ", " \-\-help
Print help and exit.
.TP
.BR \-v ", " \-\-version
Print version and exit.
.TP
.BR \-x ", " \-\-xdisplay=\fIhostname:number.screen_number\fR
Sets the xdisplay to use.
.TP
.BR \-f ", " \-\-format=\fISTRING\fR
Sets the desired output format, by default maim will attempt to determine the desired output format automatically from the output file. If that fails it defaults to a lossless png format. Currently only supports `png` or `jpg`.
.TP
.BR \-i ", " \-\-window=\fIWINDOW\fR
Sets the desired window to capture, defaults to the root window. Allows for an integer, hex, or `root` for input.
.TP
.BR \-g ", " \-\-geometry=\fIGEOMETRY\fR
Sets the region to capture, uses local coordinates from the given window. So -g 10x30-5+0 would represent the rectangle wxh+x+y where w=10, h=30, x=-5, and y=0. x and y are the upper left location of this rectangle.
.TP
.BR \-w ", " \-\-parent=\fIWINDOW\fR
By default, maim assumes the --geometry values are in respect to the provided --window (or root if not provided). This parameter overrides this behavior by making the geometry be in respect to whatever window you provide to --parent. Allows for an integer, hex, or `root` for input.
.TP
.BR \-B ", " \-\-capturebackground
By default, when capturing a window, maim will ignore anything beneath the specified window. This parameter overrides this and also captures elements underneath the window.
.TP
.BR \-d ", " \-\-delay=\fIFLOAT\fR
Sets the time in seconds to wait before taking a screenshot. Prints a simple message to show how many seconds are left before a screenshot is taken. See \-\-quiet for muting this message.
.TP
.BR \-u ", " \-\-hidecursor
By default maim super-imposes the cursor onto the image, you can disable that behavior with this flag.
.TP
.BR \-m ", " \-\-quality
An integer from 1 to 10 that determines the compression quality. 1 is the highest (and lossiest) compression available for the provided format. For example a setting of `1` with png (a lossless format) would increase filesize and decrease decoding time. While a setting of `1` on a jpeg would create a pixel mush.
.TP
.BR \-s ", " \-\-select
Enables an interactive selection mode where you may select the desired region or window before a screenshot is captured. Uses the settings below to determine the visuals and settings of slop.
.SH SLOP OPTIONS
.TP
.BR \-b ", " \-\-bordersize=\fIFLOAT\fR
Sets the selection rectangle's thickness.
.TP
.BR \-p ", " \-\-padding=\fIFLOAT\fR
Sets the padding size for the selection, this can be negative.
.TP
.BR \-t ", " \-\-tolerance=\fIFLOAT\fR
How far in pixels the mouse can move after clicking, and still be detected as a normal click instead of a click-and-drag. Setting this to 0 will disable window selections. Alternatively setting it to 9999999 would force a window selection.
.TP
.BR \-c ", " \-\-color=\fIFLOAT,FLOAT,FLOAT,FLOAT\fR
Sets the selection rectangle's color. Supports RGB or RGBA input. Depending on the system's window manager/OpenGL support, the opacity may be ignored.
.TP
.BR \-r ", " \-\-shader=\fISTRING\fR
This sets the vertex shader, and fragment shader combo to use when drawing the final framebuffer to the screen. This obviously only works when OpenGL is enabled. The shaders are loaded from ~/.config/maim. See https://github.com/naelstrof/slop for more information on how to create your own shaders.
.TP
.BR \-n ", " \-\-nodecorations=\fIINT\fR
Sets the level of aggressiveness when trying to remove window decorations. `0' is off, `1' will try lightly to remove decorations, and `2' will recursively descend into the root tree until it gets the deepest available visible child under the mouse. Defaults to `0'.
.TP
.BR \-l ", " \-\-highlight
Instead of outlining a selection, maim will highlight it instead. This is particularly useful if the color is set to an opacity lower than 1.
.TP
.BR \-D ", " \-\-nodrag
Allows you to click twice to indicate a selection, rather than click-dragging.
.TP
.BR \-q ", " \-\-quiet
Disable any unnecessary cerr output. Any warnings or info simply won't print.
.TP
.BR \-k ", " \-\-nokeyboard
Disables the ability to cancel selections with the keyboard.
.TP
.BR \-o ", " \-\-noopengl
Disables graphics hardware acceleration.
.SH EXAMPLES
Screenshot the active window and save it to the clipboard for quick pasting.
.PP
.nf
.RS
maim -i $(xdotool getactivewindow) | xclip -selection clipboard -t image/png
.RE
.fi
.PP
Save a desktop screenshot with a unique ordered timestamp in the Pictures folder.
.PP
.nf
.RS
maim ~/Pictures/$(date +%s).png
.RE
.fi
.PP
Save screenshot to the Pictures folder and add it to the clipboard at the same time.
.PP
.nf
.RS
maim | tee ~/Pictures/$(date +%s).png | xclip -selection clipboard -t image/png
.RE
.fi
.PP
Prompt for a region to screenshot. Add a fancy shadow to it, then save it to shadow.png.
.PP
.nf
.RS
maim -s | convert - \\( +clone -background black -shadow 80x3+5+5 \\) +swap -background none -layers merge +repage shadow.png
.RE
.fi
.PP
.SH SEE ALSO
.BR slop(1)
.SH BUGS
No known bugs.
.SH AUTHOR
Dalton Nell (naelstrof@gmail.com)
